<a href="https://colab.research.google.com/github/RKumarAccount/MyPractice/blob/main/EDA_done.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [7]:
df_emp=pd.read_excel('/content/Rawdata.xlsx')
df_emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [8]:
df_emp.head()

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year

In [9]:
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [10]:
df_emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [11]:
df_emp['Salary']

0     5^00#0
1    10%%000
2    1$5%000
3     2000^0
4     30000-
5    6000^$0
Name: Salary, dtype: object

In [14]:
df_emp[['Salary','Exp']]

    Salary      Exp
0   5^00#0       2+
1  10%%000       <3
2  1$5%000   4> yrs
3   2000^0      NaN
4   30000-  5+ year
5  6000^$0      10+

In [15]:
df_emp['Name']

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: object

In [18]:
df_emp['Name']=df_emp['Name'].str.replace(r'\W','',regex=True)

In [19]:
df_emp['Name']

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: object

In [21]:
df_emp

    Name          Domain       Age   Location   Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy         Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam      Statistics     67-yr        NaN   30000-  5+ year
5    Kim             NLP      55yr      Delhi  6000^$0      10+

In [24]:
df_emp['Domain'].str.replace(r'\W','',regex=True)

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: object

In [25]:
df_emp['Domain']=df_emp['Domain'].str.replace(r'\W','',regex=True)
df_emp

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year
5    Kim          NLP      55yr      Delhi  6000^$0      10+

In [27]:
df_emp['Age'].str.extract(r'(\d+)')

     0
0   34
1   45
2  NaN
3  NaN
4   67
5   55

In [28]:
df_emp['Age']=df_emp['Age'].str.extract(r'(\d+)')
df_emp

    Name       Domain  Age   Location   Salary      Exp
0   Mike  Datascience   34     Mumbai   5^00#0       2+
1  Teddy      Testing   45  Bangalore  10%%000       <3
2   Umar  Dataanalyst  NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics  NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics   67        NaN   30000-  5+ year
5    Kim          NLP   55      Delhi  6000^$0      10+

In [30]:
df_emp['Salary'].str.replace(r'\W','',regex=True)
#df_emp

0     5000
1    10000
2    15000
3    20000
4    30000
5    60000
Name: Salary, dtype: object

In [31]:
df_emp['Salary']=df_emp['Salary'].str.replace(r'\W','',regex=True)
df_emp

    Name       Domain  Age   Location Salary      Exp
0   Mike  Datascience   34     Mumbai   5000       2+
1  Teddy      Testing   45  Bangalore  10000       <3
2   Umar  Dataanalyst  NaN        NaN  15000   4> yrs
3   Jane    Analytics  NaN   Hyderbad  20000      NaN
4  Uttam   Statistics   67        NaN  30000  5+ year
5    Kim          NLP   55      Delhi  60000      10+

In [32]:
df_emp['Exp'].str.extract(r'(\d+)')
#df_emp

     0
0    2
1    3
2    4
3  NaN
4    5
5   10

In [33]:
df_emp['Exp']=df_emp['Exp'].str.extract(r'(\d+)')
df_emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [35]:
import numpy as np
df_emp['Age']=df_emp['Age'].fillna(np.mean(pd.to_numeric(df_emp['Age'])))
df_emp

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25        NaN  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  NaN
4  Uttam   Statistics     67        NaN  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [36]:
df_emp['Age'].astype(int)

0    34
1    45
2    50
3    50
4    67
5    55
Name: Age, dtype: int64

In [37]:
df_emp['Age']=df_emp['Age'].astype(int)
df_emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50        NaN  15000    4
3   Jane    Analytics   50   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [42]:
df_emp['Location'].fillna(df_emp['Location'].mode()[0])

0       Mumbai
1    Bangalore
2    Bangalore
3     Hyderbad
4    Bangalore
5        Delhi
Name: Location, dtype: object

In [43]:
df_emp['Location']=df_emp['Location'].fillna(df_emp['Location'].mode()[0])
df_emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50  Bangalore  15000    4
3   Jane    Analytics   50   Hyderbad  20000  NaN
4  Uttam   Statistics   67  Bangalore  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [45]:
df_emp['Exp'].fillna(np.mean(pd.to_numeric(df_emp['Exp'])))

0      2
1      3
2      4
3    4.8
4      5
5     10
Name: Exp, dtype: object

In [46]:
df_emp['Exp']=df_emp['Exp'].fillna(np.mean(pd.to_numeric(df_emp['Exp'])))
df_emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50  Bangalore  15000    4
3   Jane    Analytics   50   Hyderbad  20000  4.8
4  Uttam   Statistics   67  Bangalore  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [47]:
df_emp['Exp'].astype(int)

0     2
1     3
2     4
3     4
4     5
5    10
Name: Exp, dtype: int64

In [48]:
df_emp['Exp']=df_emp['Exp'].astype(int)
df_emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50  Bangalore  15000    4
3   Jane    Analytics   50   Hyderbad  20000    4
4  Uttam   Statistics   67  Bangalore  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [54]:
df_emp['Salary']=df_emp['Salary'].astype(int)
df_emp

    Name       Domain  Age   Location  Salary  Exp
0   Mike  Datascience   34     Mumbai    5000    2
1  Teddy      Testing   45  Bangalore   10000    3
2   Umar  Dataanalyst   50  Bangalore   15000    4
3   Jane    Analytics   50   Hyderbad   20000    4
4  Uttam   Statistics   67  Bangalore   30000    5
5    Kim          NLP   55      Delhi   60000   10

In [55]:
df_clean=df_emp.copy()
df_clean

    Name       Domain  Age   Location  Salary  Exp
0   Mike  Datascience   34     Mumbai    5000    2
1  Teddy      Testing   45  Bangalore   10000    3
2   Umar  Dataanalyst   50  Bangalore   15000    4
3   Jane    Analytics   50   Hyderbad   20000    4
4  Uttam   Statistics   67  Bangalore   30000    5
5    Kim          NLP   55      Delhi   60000   10

In [56]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       6 non-null      int64
 3   Location  6 non-null      object
 4   Salary    6 non-null      int64
 5   Exp       6 non-null      int64
dtypes: int64(3), object(3)
memory usage: 420.0+ bytes

In [57]:
df_clean['Name']=df_clean['Name'].astype('category')
df_clean['Domain']=df_clean['Domain'].astype('category')
df_clean['Location']=df_clean['Location'].astype('category')
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      category
 1   Domain    6 non-null      category
 2   Age       6 non-null      int64
 3   Location  6 non-null      category
 4   Salary    6 non-null      int64
 5   Exp       6 non-null      int64
dtypes: category(3), int64(3)
memory usage: 938.0 bytes